- hosts: all
  tasks:

  - name: Install requirements
    apt:
      name: 
        - autofs
        - python3-pip
        - jq
        - python3 
        - python3-dev 
        - git 
        - curl
        - wget
        - python3-venv
        - lsb-release
        - dstat
        - nload
        - dnsutils
        - g++
        - gcc
        - firefox
        - meld
        - cowsay
        - lolcat
      state: latest
      update_cache: yes

  - name: Remove old Docker version
    apt:
      name:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent

  - name: Install Docker deps
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - gnupg
        - gnupg-agent
        - software-properties-common
      state: latest
      update_cache: yes

  - name: Add Docker’s official GPG key
    apt_key:
      url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
      state: present

  - name: Add Docker's repository into sources list
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
      state: present

  - name: Install Docker engine community
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest

  - name: Enable services
    systemd:
      name: "{{ item }}" 
      enabled: yes
      state: started
    loop:
      - docker

  - name: Update pip
    pip:
      name: 
        - pip
      executable: pip3
      state: latest

  - name: Install docker-compose
    pip:
      name: 
        - docker-compose
      executable: pip3
      state: latest
