---
- name: "Compile Valgrind {{ valg_version }}"
  hosts: localhost
  vars:
    work_dir: ".installation"
    valg_version: valgrind-3.19.0
    valg_tarball_file: "{{ valg_version }}.tar.bz2"
    valg_tarball_url: "https://sourceware.org/pub/valgrind/{{ valg_tarball_file }}"
    valg_install_dir: "{{ work_dir }}/{{ valg_version }}"
    valg_custom_modules: "--prefix={{ work_dir }}/bin"

  tasks:
  - name: Prepare installation workdir
    file:
      state: directory
      path: "{{ work_dir }}"

  - name: Removing Valgrind in repo
    apt: 
      name: valgrind
      state: absent

  - name: Installing Valgrind Dependencies
    become: yes
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - automake
      - gcc
      - g++
      - git

  - name: Downloading Valgrind Source
    get_url:
      url: "{{ valg_tarball_url }}"
      dest: "{{ work_dir }}/{{ valg_tarball_file }}"
    register: valg_source

  - name: Unpacking Valgrind
    shell: "bzip2 -d -c {{ valg_tarball_file }} | tar xvf -"
    args:
      chdir: "{{ work_dir }}"
    when: valg_source.changed
    register: valg_source_unpack

  - name: Configuring Valgrind
    shell: "./autogen.sh && ./configure {{ valg_custom_modules }}"
    args:
      chdir: "{{ valg_install_dir }}"
    when: valg_source_unpack.changed
    register: valg_configure

  - name: Removing files
    file:
      state: absent  
      path: "{{ valg_source.dest }}"
    when: valg_configure.changed

  - name: Installing Valgrind
    become: yes
    shell: make && make install
    args:
      chdir: "{{ valg_install_dir }}"
    when: valg_configure.changed
